'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServicioEtiquetas
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://erp.natural.gs/", ConfigurationName:="ServicioEtiquetas.EtiquetasSoap")>  _
    Public Interface EtiquetasSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://erp.natural.gs/GetEtiquetaDeCajasByPedidoid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetEtiquetaDeCajasByPedidoid(ByVal pedidoid As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://erp.natural.gs/GetEtiquetaDeCajasByPedidoid", ReplyAction:="*")>  _
        Function GetEtiquetaDeCajasByPedidoidAsync(ByVal pedidoid As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface EtiquetasSoapChannel
        Inherits ServicioEtiquetas.EtiquetasSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EtiquetasSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServicioEtiquetas.EtiquetasSoap)
        Implements ServicioEtiquetas.EtiquetasSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetEtiquetaDeCajasByPedidoid(ByVal pedidoid As Integer) As System.Data.DataSet Implements ServicioEtiquetas.EtiquetasSoap.GetEtiquetaDeCajasByPedidoid
            Return MyBase.Channel.GetEtiquetaDeCajasByPedidoid(pedidoid)
        End Function
        
        Public Function GetEtiquetaDeCajasByPedidoidAsync(ByVal pedidoid As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServicioEtiquetas.EtiquetasSoap.GetEtiquetaDeCajasByPedidoidAsync
            Return MyBase.Channel.GetEtiquetaDeCajasByPedidoidAsync(pedidoid)
        End Function
    End Class
End Namespace
